/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./components/base/BaseAvatar.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    CategoryList: typeof import('./components/common/CategoryList.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    LoginModal: typeof import('./components/common/LoginModal.vue')['default']
    PostCard: typeof import('./components/common/PostCard.vue')['default']
    PostList: typeof import('./components/layout/PostList.vue')['default']
    ProfileCard: typeof import('./components/common/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    TagCloud: typeof import('./components/common/TagCloud.vue')['default']
    TheBackground: typeof import('./components/common/TheBackground.vue')['default']
    TheFooter: typeof import('./components/layout/TheFooter.vue')['default']
    TheNavbar: typeof import('./components/layout/TheNavbar.vue')['default']
    WelcomeBanner: typeof import('./components/common/WelcomeBanner.vue')['default']
  }
}
