name: Build

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
      - ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.22.0
          run_install: true

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'

      - name: 构建产物
        run: pnpm run build

      - name: 打包上传
        uses: actions/upload-artifact@v4
        with:
          name: olive-blog-vue-v1
          path: ./dist
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: production
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Runner OS: $RUNNER_OS"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "Host: ${{ secrets.HOST }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "PORT: ${{ secrets.PORT }}"
          
          # 打印 secrets 的长度（不会暴露内容，但可验证是否设置）
          echo "SSH_KEY length: ${#SSH_PRIVATE_KEY}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: olive-blog-vue-v1
          path: ./dist

      - name: 通过 SSH 复制文件
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/opt/docker/nginx/www/blog-v1"
          strip_components: 1
          rm: true
      
      - name: 重启nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker exec nginx nginx -s reload